properties:
  exportVersion: 1.0
  name: '{{projectName}}'
  space: ref{project.current.spaceId}
  type: DATA_MOVEMENT
  description: with replication, lake landing, transformation
  platformType: SNOWFLAKE
  platformConnection: '{{platformConnection}}'
  cloudStagingConnection: '{{cloudStagingConnection}}'
  snowflakeStorageIntegration: ''
