properties:
  exportVersion: 1.0
  name: '{{projectName}}'
  space: ref{project.current.spaceId}
  type: DATA_PIPELINE
  platformType: SNOWFLAKE
  platformConnection: '{{platformConnection}}'
  cloudStagingConnection: '{{cloudStagingConnection}}'
  snowflakeStorageIntegration: ''
settings:
  artifactsNaming:
    prefixSchema: '{{project.current.prefixSchema}}'
