properties:
  exportVersion: 1.0
  name: '{{projectName}}'
  space: ref{project.current.spaceId}
  type: DATA_PIPELINE
  description: ''
  platformType: SNOWFLAKE
  platformConnection: '{{platformConnection}}'
  cloudStagingConnection: '{{cloudStagingConnection}}'
  snowflakeStorageIntegration: ''
settings:
  artifactsNaming:
    suffixLiveViews: __live
    suffixChangesView: __changes
    suffixCurrentView: ''
    suffixHistoryViews: __history
    suffixLiveHistoryViews: __live_history
    suffixInternalSchema: __internal
    prefixHeaderColumns: hdr__
    prefixSchema: '{{project.current.prefixSchema}}'
    defaultSchemaNameOption: LOWER_CASE
